### ISSUE TITLE
Testing for presence in prototype doesn't always work

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#380] opened 2020-08-28 23:27 UTC
It looks like testing for the presence of the attribute/operation in the object's prototype will not always get the correct test results, resulting in a number of false negatives for all browsers.  There's a few possible solutions to this:

- Create overrides for all the browsers.  This should be a last resort, rather than a first.
- Create custom tests for all of these uninitialized properties.  It feels like a lot of extra steps, but it may be what we need to do.
- Always construct the objects or otherwise get them.  This will involve a bit of a refactoring of the harness.js and build.js.

**Comment by foolip** [comment] 2020-08-29 05:13
Which browsers does this affect other than Chrome <43? I guess Safari also had the same problem at some point?

One simple thing we can do to avoid getting bad data is to only trust attributes if we see that some ancient attribute is on the relevant prototype, maybe Document.prototype.title? We can do source code archeology to find one that goes back to the very beginning in all engines.

**Comment by vinyldarkscratch** [comment] 2020-08-29 11:14
This also seemed to affect Firefox <36.  Although...maybe that can be resolved by bumping the cutoff version up some more?

**Comment by foolip** [comment] 2020-08-31 11:10
Do you have an example of the problem in Edge? I tested `'localName' in Element.prototype` in Edge 18 and it returns true. So it doesn't look like the same issue as Chrome <43 had.

**Comment by vinyldarkscratch** [comment] 2020-08-31 15:44
I can't remember exactly which API I saw the issue in...  I'll have to do another sweep and take a look.  (I believe it was one of the geometry APIs).

**Comment by foolip** [comment] 2020-08-31 18:39
There are still some attributes which should be on the instances only, like document.location has the LegacyUnforgeable extended attribute.

Engines have had things like this for security reasons (ish) and perhaps some attributes that you wouldn't have expected have behaved this way.

**Comment by vinyldarkscratch** [comment] 2020-09-01 07:34
That makes sense.  Now that the custom test generation is improved as well, we can more commonly test for the presence in the instances rather than the prototype in select APIs.

**Comment by foolip** [comment] 2021-03-19 18:51
Let's consider this a dupe of https://github.com/foolip/mdn-bcd-collector/issues/523.

**Closed by foolip** 2021-03-19 18:51 UTC
Labels: Priority: High
