### ISSUE TITLE
Support 'preview' in update-bcd

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#1834] opened 2022-02-25 00:13 UTC
This currently leads to errors, and I don't understand that part of `update-bcd`. Hopefully someone else remembers how it works.

**Comment by foolip** [comment] 2022-02-25 07:42
Do you think we should use that whenever we see a Safari version that is newer than what's stable in BCD's safari.json? That would mean it's used for both STP and beta, is that OK?

**Comment by gsnedders** [comment] 2022-02-25 14:17
We've been using mdn-bcd-collector to update things at the point of beta releases. There's a few cases I think we need to care about:

 * `false` -> `preview` upon STP release,
 * `preview` -> `[version]` upon beta release, and
 * `false` -> `[version]` upon beta release.

As such, I don't think using preview > stable works particularly well. At the same time, e.g., at present both STP 140 and Safari 15.4 beta claim to be `Version/15.4`, which means I don't think there's any way to distinguish them from UA string.

I think a more concrete proposal might be to have a `--treat-as-preview VERSION` option, which isn't ideal because it doesn't allow for beta & preview to be updated in a single run, but might be the best compromise currently?

**Comment by foolip** [comment] 2022-03-01 10:20
`--treat-as-preview` seems like a workable approach. @queengooborg WDYT?

**Comment by queengooborg** [comment] 2022-03-02 12:16
I don't have much of an understanding of the problem to provide an opinion on this, but it seems good to me!

**Comment by queengooborg** [comment] 2022-04-14 07:42
I just ran `update-bcd`, and I now see what the problem is -- when the script gets to an entry that is set to `preview`, it crashes because it assumes that a string is a version number to parse.  I should have an easy fix for this that doesn't need an argument!

**Closed** 2022-04-14 08:04 UTC
Labels: enhancement
